---
Name: iqsocialmedia
After:
  - 'framework/*'
  - 'cms/*'
Before:
  - 'mysite/*'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IqSocialMedia\Extensions\IqSocialMediaSiteConfigExtension
---